movie_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from django.conf.urls.static import static
from movies.views import Login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls', namespace="movies")),
    # path('', LoginView, ({'template_name': 'index.html'})),

    # path('logout/', auth_views.logout_then_login, {'next_page': '/'}, name='logout'),
    path('api/{}/'.format(settings.API_VERSION), include('movies.api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from movies.api.viewsets import TodoViewSet
from . import views
from movies.views import Login, Logout, BestView, IndexView, MovieDetailView, DownloadView

app_name = 'movies'
urlpatterns = [
    path('', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('principal/',  IndexView.as_view(), name='index'),
    path('best/',  BestView.as_view(), name='index2'),
    # path('single/', views.single, name='single'),
    path('movie/<slug>/', MovieDetailView.as_view(), name='single'),
    # path('movie/<slug>/', MovieDetailView.as_view(), name='movie-detail'),
    path('horror/', views.horror, name='horror'),
    path('genres/', views.genres, name='genres'),
    path('comedy/', views.comedy, name='comedy'),
    path('list/', views.list_view, name='list'),
    path('download/', DownloadView.as_view(), name='download'),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth')
]

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
    <!-- header -->
	<div class="header">
		<div class="container">
			<div class="w3layouts_logo">
				<a href="{% url 'movies:index' %}"><h1>One<span>Movies</span></h1></a>
			</div>
			<!--div class="w3_search">
				<form action="#" method="post">
					<input type="text" name="Search" placeholder="Search" required="">
					<input type="submit" value="Go">
				</form>
			</div-->
			<div class="w3l_sign_in_register log_in">
				<ul>
					<li><i class="fa fa-phone" aria-hidden="true"></i> (+000) 123 345 653</li>
					<li><a href="#" data-toggle="modal" data-target="#myModal">Login</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //header -->
<!-- bootstrap-pop-up -->
	<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					Sign In & Sign Up
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<section>
					<div class="modal-body">
						<div class="w3_login_module">
							<div class="module form-module">
							  <div class="toggle"><i class="fa fa-times fa-pencil"></i>
								<div class="tooltip">Click Me</div>
							  </div>
							  <div class="form">
								<h3>Login to your account</h3>
								<form action="{% url 'movies:login' %}" method="post">
                                    {% csrf_token %}
								  <input type="text" name="username" placeholder="Username" required="">
								  <input type="password" name="password" placeholder="Password" required="">
								  <input type="submit" value="Login">
								</form>
							  </div>
							  <div class="form">
								<h3>Create an account</h3>
								<form action="#" method="post">
                                    {% csrf_token %}
								  <input type="text" name="Username" placeholder="Username" required="">
								  <input type="password" name="Password" placeholder="Password" required="">
								  <input type="email" name="Email" placeholder="Email Address" required="">
								  <input type="text" name="Phone" placeholder="Phone Number" required="">
								  <input type="submit" value="Register">
								</form>
							  </div>
							  <div class="cta"><a href="#">Forgot your password?</a></div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
<!-- //bootstrap-pop-up -->
{% endblock %}
{% block slider %}{% endblock %}
{% block banner %}{% endblock %}
{% comment %}{% block general %}{% endblock %}{% endcomment %}

{% block single %}{% endblock %}

templates/principal.html
{% extends "base.html" %}
{% load staticfiles %}

{% block slider %}

<!-- banner -->
	<div id="slidey" style="display:none;">
		<ul>
            {% for best_rated_movie in best_rated_movie_0 %}
			    <li><img src="{{ best_rated_movie.img.url }}" alt="{{ best_rated_movie.title }}"><h1 class="rate">{{ best_rated_value_0|floatformat:1 }} / 10</h1><h1 class='title'>{{ best_rated_movie.title }}</h1><p class='description'>{{ best_rated_movie.detail }}</p></li>
            {% endfor %}
			{% for best_rated_movie in best_rated_movie_1 %}
			    <li><img src="{{ best_rated_movie.img.url }}" alt="{{ best_rated_movie.title }}"><h1 class="rate">{{ best_rated_value_1|floatformat:1 }} / 10</h1><h1 class='title'>{{ best_rated_movie.title }}</h1><p class='description'>{{ best_rated_movie.detail }}</p></li>
            {% endfor %}
            {% for best_rated_movie in best_rated_movie_2 %}
			    <li><img src="{{ best_rated_movie.img.url }}" alt="{{ best_rated_movie.title }}"><h1 class="rate">{{ best_rated_value_2|floatformat:1 }} / 10</h1><h1 class='title'>{{ best_rated_movie.title }}</h1><p class='description'>{{ best_rated_movie.detail }}</p></li>
            {% endfor %}
            {% for best_rated_movie in best_rated_movie_3 %}
			    <li><img src="{{ best_rated_movie.img.url }}" alt="{{ best_rated_movie.title }}"><h1 class="rate">{{ best_rated_value_3|floatformat:1 }} / 10</h1><h1 class='title'>{{ best_rated_movie.title }}</h1><p class='description'>{{ best_rated_movie.detail }}</p></li>
            {% endfor %}
            {% for best_rated_movie in best_rated_movie_4 %}
			    <li><img src="{{ best_rated_movie.img.url }}" alt="{{ best_rated_movie.title }}"><h1 class="rate">{{ best_rated_value_4|floatformat:1 }} / 10</h1><h1 class='title'>{{ best_rated_movie.title }}</h1><p class='description'>{{ best_rated_movie.detail }}</p></li>
            {% endfor %}
		</ul>
    </div>
<!-- //banner -->
{% endblock %}
{% block single %}{% endblock %}

templates/pruebas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

<div class="container">
  <h2>Modal Example</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal2">Open Modal</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

<!-- header -->
	<div class="header">
		<div class="container">
			<div class="w3layouts_logo">
				<a href="principal.html"><h1>One<span>Movies</span></h1></a>
			</div>
			<div class="w3_search">
				<form action="#" method="post">
					<input type="text" name="Search" placeholder="Search" required="">
					<input type="submit" value="Go">
				</form>
			</div>
			<div class="w3l_sign_in_register">
				<ul>
					<li><i class="fa fa-phone" aria-hidden="true"></i> (+000) 123 345 653</li>
					<li><a href="#" data-toggle="modal" data-target="#myModal">Login</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //header -->
<!-- bootstrap-pop-up -->
	<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					Sign In & Sign Up
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<section>
					<div class="modal-body">
						<div class="w3_login_module">
							<div class="module form-module">
							  <div class="toggle"><i class="fa fa-times fa-pencil"></i>
								<div class="tooltip">Click Me</div>
							  </div>
							  <div class="form">
								<h3>Login to your account</h3>
								<form action="#" method="post">
								  <input type="text" name="Username" placeholder="Username" required="">
								  <input type="password" name="Password" placeholder="Password" required="">
								  <input type="submit" value="Login">
								</form>
							  </div>
							  <div class="form">
								<h3>Create an account</h3>
								<form action="#" method="post">
								  <input type="text" name="Username" placeholder="Username" required="">
								  <input type="password" name="Password" placeholder="Password" required="">
								  <input type="email" name="Email" placeholder="Email Address" required="">
								  <input type="text" name="Phone" placeholder="Phone Number" required="">
								  <input type="submit" value="Register">
								</form>
							  </div>
							  <div class="cta"><a href="#">Forgot your password?</a></div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>

  <script src="{%  static 'js/jquery-2.1.4.min.js' %}"></script>
  <script src="{%  static 'js/bootstrap.min.js' %}"></script>
</body>
</html>